// src/app/library/library.component.ts
import {
  AfterViewInit,
  Component,
  OnDestroy,
  OnInit,
  QueryList,
  ViewChildren,
  ChangeDetectionStrategy
} from '@angular/core';
import { EventService } from '../eventservice/event.service';
import { IGadget } from '../gadgets/common/gadget-common/gadget-base/gadget.model';
import { LibraryService } from './library.service';
import { AppConfigService } from '../app-config/app-config.service';
import { CdkVirtualScrollViewport, CdkFixedSizeVirtualScroll, CdkVirtualForOf } from '@angular/cdk/scrolling';
import { MatCard, MatCardHeader, MatCardAvatar, MatCardTitle, MatCardSubtitle, MatCardContent, MatCardActions } from '@angular/material/card';
import { NgStyle } from '@angular/common';
import { MatMiniFabButton, MatIconButton } from '@angular/material/button';
import { MatIcon } from '@angular/material/icon';
import { MatTooltip } from '@angular/material/tooltip';
import { Subscription } from 'rxjs';

@Component({
    selector: 'app-library',
    templateUrl: './library.component.html',
    styleUrls: ['./library.component.scss'],
    changeDetection: ChangeDetectionStrategy.Eager,
    imports: [CdkVirtualScrollViewport, CdkFixedSizeVirtualScroll, CdkVirtualForOf, MatCard, NgStyle, MatCardHeader, MatCardAvatar, MatCardTitle, MatCardSubtitle, MatCardContent, MatCardActions, MatMiniFabButton, MatIcon, MatIconButton, MatTooltip]
})
export class LibraryComponent implements OnInit, AfterViewInit, OnDestroy {
  // QueryList rather than a single @ViewChild: the virtual-scroll viewport only
  // exists in the DOM in the expanded (non-collapsed) template branch, so it's
  // created and destroyed as the panel toggles, not just once at startup - see
  // observeViewport() below for why that matters.
  @ViewChildren(CdkVirtualScrollViewport) viewportQuery!: QueryList<CdkVirtualScrollViewport>;
  private resizeObserver?: ResizeObserver;
  private viewportQuerySub?: Subscription;
  private collapsedSub?: Subscription;
  collapsed = false;
  colors = [
    '#FF5733', '#33FF57', '#3357FF', '#F1C40F', '#8E44AD', '#E74C3C',
    '#3498DB', '#2ECC71', '#1ABC9C', '#9B59B6', '#34495E', '#16A085',
    '#F39C12', '#D35400', '#C0392B', '#7F8C8D', '#BDC3C7', '#95A5A6',
    '#2980B9', '#27AE60', '#8E44AD', '#2C3E50', '#F4D03F', '#E67E22',
    '#D35400', '#1ABC9C', '#2ECC71', '#E74C3C', '#9B59B6', '#34495E'
  ];

  constructor(
    private libraryService: LibraryService,
    private eventService: EventService,
    private appConfigService: AppConfigService
  ) {}

  library!: IGadget[];
  ngOnInit(): void {
    this.getLibrary();
    this.collapsedSub = this.appConfigService.libraryPanelCollapsed$.subscribe((value) => {
      this.collapsed = value;
    });
  }

  ngAfterViewInit(): void {
    this.observeViewport();
    // The viewport only exists while the panel is expanded, so it's created
    // fresh (as a new element) each time the panel toggles out of collapsed
    // mode - re-attach the resize observer whenever that happens, not just
    // once at startup, or expanding a panel that started collapsed would
    // silently lose this workaround.
    this.viewportQuerySub = this.viewportQuery.changes.subscribe(() => this.observeViewport());
  }

  /**
   * CdkVirtualScrollViewport measures its container once when it's created.
   * This panel lives inside a mat-drawer that animates open from 0 width, so
   * that initial measurement is stale/undersized — it silently renders only
   * enough items to fill that small initial size (e.g. 2 of 6) even though
   * there's plenty of room once the drawer finishes opening. Re-measure
   * whenever the panel's actual size changes.
   */
  private observeViewport(): void {
    this.resizeObserver?.disconnect();
    const viewport = this.viewportQuery.first;
    if (!viewport) return;
    this.resizeObserver = new ResizeObserver(() => {
      viewport.checkViewportSize();
    });
    this.resizeObserver.observe(viewport.elementRef.nativeElement);
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    this.viewportQuerySub?.unsubscribe();
    this.collapsedSub?.unsubscribe();
  }

  getLibrary() {
    this.libraryService.getLibrary().subscribe((libraryData) => {
      this.library = [...libraryData].sort((a, b) => a.title.localeCompare(b.title));
    });
  }

  private lastAddTime = 0;

  addGadget(gadgetData: IGadget) {
    const now = Date.now();
    if (now - this.lastAddTime < 1000) return;
    this.lastAddTime = now;
    this.eventService.emitLibraryAddGadgetEvent({ data: gadgetData });
  }

  close() {
    this.eventService.emitCloseLibraryPanelEvent();
  }

  toggleCollapsed() {
    this.appConfigService.toggleLibraryPanelCollapsed();
  }
}

<div class="library-panel">
  <div class="library-panel-header" [class.collapsed]="collapsed">
    @if (!collapsed) {
      <span class="library-panel-title">Add Tool ({{ library?.length }})</span>
    }
    <div class="library-panel-header-actions">
      <button mat-icon-button class="library-panel-header-btn" (click)="toggleCollapsed()"
        [matTooltip]="collapsed ? 'Expand' : 'Collapse'" matTooltipPosition="left"
        [attr.aria-label]="collapsed ? 'Expand gadget library panel' : 'Collapse gadget library panel'">
        <mat-icon>{{ collapsed ? 'chevron_left' : 'chevron_right' }}</mat-icon>
      </button>
      <button mat-icon-button class="library-panel-header-btn library-panel-close" (click)="close()" aria-label="Close gadget library panel">
        <mat-icon>close</mat-icon>
      </button>
    </div>
  </div>

  <div class="library-panel-body">
    @if (collapsed) {
      <div class="library-icon-rail">
        @for (gadget of library; track gadget.componentType) {
          <button mat-icon-button class="library-icon-button"
            [matTooltip]="gadget.title" matTooltipPosition="left"
            [attr.aria-label]="'Add ' + gadget.title"
            (click)="addGadget(gadget)">
            <mat-icon [ngStyle]="{color: colors[$index]}">{{ gadget.icon }}</mat-icon>
          </button>
        }
      </div>
    } @else {
      <cdk-virtual-scroll-viewport itemSize="132" class="library-viewport">
        <mat-card class="library-card"
          *cdkVirtualFor="let gadget of library; let idx = index"
          [ngStyle]="{'border-top-color': colors[idx]}">
          <button mat-icon-button class="library-card-add-btn" (click)="addGadget(gadget)"
            [matTooltip]="'Add ' + gadget.title" [attr.aria-label]="'Add ' + gadget.title">
            <mat-icon>{{ gadget.actions[0].name }}</mat-icon>
          </button>
          <mat-card-header>
            <mat-icon mat-card-avatar class="library-icon">{{ gadget.icon }}</mat-icon>
            <mat-card-title>{{ gadget.title }}</mat-card-title>
            <mat-card-subtitle>{{ gadget.subtitle }}</mat-card-subtitle>
          </mat-card-header>
          <mat-card-content>
            {{ gadget.description }}
          </mat-card-content>
        </mat-card>
      </cdk-virtual-scroll-viewport>
    }
  </div>
</div>

// web/hosts/react/src/app/library/Library.tsx
import { useEffect, useRef, useState } from 'react';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardHeader from '@mui/material/CardHeader';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import { appConfigService } from '../app-config/app-config.service';
import { eventService } from '../eventservice/event.service';
import { useObservableValue } from 'src/lib/useObservable';
import { MatIcon } from '../shared/mat-icon/MatIcon';
import { libraryService } from './library.service';
import type { IGadget } from '../gadgets/common/gadget-common/gadget-base/gadget.model';
import './Library.css';

const COLORS = [
  '#FF5733', '#33FF57', '#3357FF', '#F1C40F', '#8E44AD', '#E74C3C',
  '#3498DB', '#2ECC71', '#1ABC9C', '#9B59B6', '#34495E', '#16A085',
  '#F39C12', '#D35400', '#C0392B', '#7F8C8D', '#BDC3C7', '#95A5A6',
  '#2980B9', '#27AE60', '#8E44AD', '#2C3E50', '#F4D03F', '#E67E22',
  '#D35400', '#1ABC9C', '#2ECC71', '#E74C3C', '#9B59B6', '#34495E',
];

/**
 * Ported from armature-ui's LibraryComponent. CdkVirtualScrollViewport's
 * measure-inside-an-animating-drawer workaround doesn't carry over — the
 * library here is a plain scrolling list rather than a virtualized one
 * (library.json holds ~11 gadgets, well within "just render them all").
 */
export function Library() {
  const [library, setLibrary] = useState<IGadget[]>([]);
  const collapsed = useObservableValue(
    appConfigService.libraryPanelCollapsed$,
    () => appConfigService.libraryPanelCollapsed
  );
  const lastAddTime = useRef(0);

  useEffect(() => {
    libraryService.getLibrary().subscribe((libraryData) => {
      setLibrary([...libraryData].sort((a, b) => a.title.localeCompare(b.title)));
    });
  }, []);

  function addGadget(gadgetData: IGadget) {
    const now = Date.now();
    if (now - lastAddTime.current < 1000) return;
    lastAddTime.current = now;
    eventService.emitLibraryAddGadgetEvent({ data: gadgetData });
  }

  function close() {
    eventService.emitCloseLibraryPanelEvent();
  }

  function toggleCollapsed() {
    appConfigService.toggleLibraryPanelCollapsed();
  }

  return (
    <div className="library-panel">
      <div className={['library-panel-header', collapsed ? 'collapsed' : ''].filter(Boolean).join(' ')}>
        {!collapsed && <span className="library-panel-title">Add Tool ({library.length})</span>}
        <div className="library-panel-header-actions">
          <Tooltip title={collapsed ? 'Expand' : 'Collapse'} placement="left">
            <IconButton
              className="library-panel-header-btn"
              onClick={toggleCollapsed}
              size="small"
              aria-label={collapsed ? 'Expand gadget library panel' : 'Collapse gadget library panel'}
            >
              <MatIcon>{collapsed ? 'chevron_left' : 'chevron_right'}</MatIcon>
            </IconButton>
          </Tooltip>
          <IconButton
            className="library-panel-header-btn library-panel-close"
            onClick={close}
            size="small"
            aria-label="Close gadget library panel"
          >
            <MatIcon>close</MatIcon>
          </IconButton>
        </div>
      </div>

      <div className="library-panel-body">
        {collapsed ? (
          <div className="library-icon-rail">
            {library.map((gadget, index) => (
              <Tooltip key={gadget.componentType} title={gadget.title} placement="left">
                <IconButton
                  className="library-icon-button"
                  onClick={() => addGadget(gadget)}
                  aria-label={`Add ${gadget.title}`}
                >
                  <MatIcon style={{ color: COLORS[index % COLORS.length] }}>{gadget.icon}</MatIcon>
                </IconButton>
              </Tooltip>
            ))}
          </div>
        ) : (
          <div className="library-viewport">
            {library.map((gadget, index) => (
              <Card
                key={gadget.componentType}
                className="library-card"
                style={{ borderTopColor: COLORS[index % COLORS.length] }}
              >
                <Tooltip title={`Add ${gadget.title}`}>
                  <IconButton
                    className="library-card-add-btn"
                    onClick={() => addGadget(gadget)}
                    aria-label={`Add ${gadget.title}`}
                    size="small"
                  >
                    <MatIcon>{gadget.actions?.[0]?.name ?? 'add'}</MatIcon>
                  </IconButton>
                </Tooltip>
                <CardHeader
                  avatar={<MatIcon className="library-icon">{gadget.icon}</MatIcon>}
                  title={gadget.title}
                  subheader={gadget.subtitle}
                />
                <CardContent>{gadget.description}</CardContent>
                {gadget.tags.length > 0 && (
                  <div className="library-card-tags">
                    {gadget.tags.map((tag) => (
                      <span key={tag.name} className="tag-pill">
                        {tag.name}
                      </span>
                    ))}
                  </div>
                )}
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
