// src/app/sidenav/sidenav.component.ts
import { Component, OnDestroy, OnInit, ViewChild, ChangeDetectionStrategy } from '@angular/core';
import { MatDrawer, MatDrawerContainer } from '@angular/material/sidenav';
import { BoardService } from '../board/board.service';
import { Hiearchy, IBoard, IBoardCollection } from '../board/board.model';
import { EventService } from '../eventservice/event.service';
import { AppConfigService } from '../app-config/app-config.service';
import { MatNavList, MatListItem, MatListItemIcon } from '@angular/material/list';
import { MatIcon } from '@angular/material/icon';
import { MatIconButton } from '@angular/material/button';
import { MatTooltip } from '@angular/material/tooltip';
import { SidelayoutComponent } from '../layout/layout.component';
import { BoardComponent } from '../board/board.component';
import { ConfigPanelComponent } from '../config-panel/config-panel.component';
import { LibraryComponent } from '../library/library.component';
import { HelpPanelComponent } from '../help-panel/help-panel.component';
import { AgentPanelComponent } from '../agent/agent-panel.component';
import { Subscription } from 'rxjs';

@Component({
    selector: 'app-sidenav',
    templateUrl: './sidenav.component.html',
    styleUrls: ['./sidenav.component.scss'],
    changeDetection: ChangeDetectionStrategy.Eager,
    imports: [MatDrawerContainer, MatDrawer, MatNavList, MatListItem, MatListItemIcon, MatIcon, MatIconButton, MatTooltip, SidelayoutComponent, BoardComponent, ConfigPanelComponent, LibraryComponent, HelpPanelComponent, AgentPanelComponent]
})
export class SidenavComponent implements OnInit, OnDestroy {
  @ViewChild('drawer') public drawer!: MatDrawer;
  @ViewChild('layout') public layout!: MatDrawer;
  @ViewChild('configPanel') public configPanel!: MatDrawer;
  @ViewChild('library') public library!: MatDrawer;
  @ViewChild('helpPanel') public helpPanel!: MatDrawer;
  @ViewChild('agentPanel') public agentPanel!: MatDrawer;
  boardData: IBoard[] = [];

  selectedBoardId: number | null = null;
  private openConfigInstanceId: number = -1;

  // The left nav (#drawer) has three widths, driven by two independent
  // controls rather than one control cycling through all three:
  //  - the toolbar hamburger (toggleMenu) only ever switches between the
  //    two *visible* rail widths, 'expanded' and 'icon' — its icon never
  //    changes, so a control that could also silently jump to "gone" was
  //    confusing.
  //  - a dedicated chevron docked to the rail's own edge (collapseNav) is
  //    the only thing that takes it to 'hidden' (0px, completely out of
  //    the way); the same edge position hosts a reveal tab (expandNav)
  //    once hidden. It's still technically always [opened] — 'hidden'
  //    animates its width to 0 rather than closing it.
  navState: 'expanded' | 'icon' | 'hidden' = 'expanded';

  // What to restore when expandNav() brings the rail back — whichever of
  // the two visible widths was showing right before it was collapsed.
  private lastVisibleNavState: 'expanded' | 'icon' = 'expanded';

  get navExpanded(): boolean {
    return this.navState === 'expanded';
  }

  /** 220 (expanded) / 64 (icon-only) — mirrors the widths in sidenav.component.scss, used to dock the collapse chevron to the rail's current right edge. */
  get navRailWidthPx(): number {
    return this.navState === 'expanded' ? 220 : 64;
  }

  // Drives .library-collapsed on .library-panel-container in
  // sidenav.component.scss, which is what actually controls the library
  // drawer's width (LibraryComponent itself just fills whatever width its
  // ancestor drawer container resolves to - it can't set that width from
  // inside, since CSS custom properties don't inherit upward).
  libraryCollapsed = false;
  private libraryCollapsedSub?: Subscription;

  constructor(
    private eventService: EventService,
    private boardService: BoardService,
    private appConfigService: AppConfigService
  ) {
    this.loadBoards();
    this.setupEventListeners();
  }

  ngOnInit(): void {
    this.libraryCollapsedSub = this.appConfigService.libraryPanelCollapsed$.subscribe((value) => {
      this.libraryCollapsed = value;
    });
  }

  ngOnDestroy(): void {
    this.libraryCollapsedSub?.unsubscribe();
  }

  /** Toolbar hamburger: switches only between the two visible rail widths. */
  toggleMenu() {
    this.navState =
      this.navState === 'hidden'
        ? this.lastVisibleNavState
        : this.navState === 'expanded'
          ? 'icon'
          : 'expanded';
    this.lastVisibleNavState = this.navState;
  }

  /** Bound to the chevron docked to the rail's edge while it's visible. */
  collapseNav() {
    this.lastVisibleNavState = this.navState === 'hidden' ? this.lastVisibleNavState : this.navState;
    this.navState = 'hidden';
  }

  /** Bound to the same edge position's reveal tab once the rail is hidden. */
  expandNav() {
    this.navState = this.lastVisibleNavState;
  }

  toggleLayout() {
    if (!this.layout.opened) {
      this.configPanel.close();
      this.library.close();
      this.helpPanel.close();
      this.agentPanel.close();
    }
    this.layout.toggle();
  }

  toggleLibrary() {
    if (!this.library.opened) {
      this.configPanel.close();
      this.layout.close();
      this.helpPanel.close();
      this.agentPanel.close();
    }
    this.library.toggle();
  }

  // Bound to (openedChange) on every mode="side" drawer except #drawer
  // (#layout, #configPanel, #library, #helpPanel, #agentPanel) - all of
  // them push/resize the board rather than overlay it, since the board sits
  // nested inside all of their content areas. mode="over" was tried for the
  // four utility panels first, but its slide is barely perceptible next to
  // #layout's — mode="side" additionally animates the board's own
  // margin/width, which is what actually reads as a real transition, not
  // just the panel itself moving. That resize is a CSS transition, not a
  // browser window resize, but ngx-charts only re-measures its container on
  // the window's native 'resize' event — so without this, gadget charts
  // stay sized for the old (drawer-open) width until an actual window
  // resize or full page reload. openedChange fires once the drawer's
  // open/close animation has finished, so the board has already reached its
  // final width by the time this dispatches.
  onPushDrawerAnimationDone() {
    window.dispatchEvent(new Event('resize'));
  }

  // #drawer no longer opens/closes (it's always [opened]="true") — expanding
  // and collapsing the icon rail instead animates its `width` via a plain
  // CSS transition, which never fires (openedChange). Native `transitionend`
  // is the equivalent "animation actually finished" signal for that case, so
  // gadget charts still get resized once the board reaches its final width.
  onNavRailTransitionEnd(event: TransitionEvent) {
    if (event.propertyName === 'width') {
      this.onPushDrawerAnimationDone();
    }
  }

  // Bound to <mat-drawer #configPanel (closed)>. Fires whenever the drawer
  // actually finishes closing — close button, backdrop click, escape key,
  // or being closed programmatically (e.g. toggleLayout() above) — so it's
  // the single reliable place to tell the gadget that was being configured
  // to exit config mode, regardless of how the panel got closed.
  onConfigPanelClosed() {
    this.eventService.emitConfigPanelClosedEvent({ data: { instanceId: this.openConfigInstanceId } });
  }

  loadBoards() {
    this.boardService.getBoardCollection().subscribe((boardCollection: IBoardCollection) => {
      this.boardData = boardCollection.boardList.filter((obj) => {
        return obj.relationship == Hiearchy.PARENT;
      });

      if (this.boardData.length === 0) {
        // Nothing left for the library/layout/config panels to act on —
        // most reachable by deleting the last remaining board while one of
        // them is open. Optional chaining: this also runs from the
        // constructor, before the drawer ViewChildren exist yet.
        this.layout?.close();
        this.library?.close();
        this.configPanel?.close();
        this.helpPanel?.close();
        this.agentPanel?.close();
      }

      if (!this.selectedBoardId) {
        this.boardService.getLastSelectedBoard().subscribe((board: IBoard) => {
          if (board && board.id != null) {
            this.selectedBoardId = board.id;
          } else if (this.boardData.length > 0) {
            this.selectedBoardId = this.boardData[0].id;
          }
        });
      }
    });
  }

  selectBoard(boardId: number) {
    this.selectedBoardId = boardId;
    this.eventService.emitBoardSelectedEvent({ data: boardId });
  }

  setupEventListeners() {
    this.eventService
      .listenForBoardMenuSideNavClickEvent()
      .subscribe((event) => {
        this.toggleMenu();
      });

    this.eventService
      .listenForBoardSideLayoutEvent().subscribe((event) => {
        this.toggleLayout();
      });

    this.eventService.listenForOpenConfigPanelEvent().subscribe((event) => {
      this.openConfigInstanceId = event.data.instanceId;
      this.layout.close();
      this.library.close();
      this.helpPanel.close();
      this.agentPanel.close();
      this.configPanel.open();
    });

    this.eventService.listenForCloseConfigPanelEvent().subscribe(() => {
      this.configPanel.close();
    });

    this.eventService.listenForLibraryOpenMenuEvent().subscribe(() => {
      this.toggleLibrary();
    });

    this.eventService.listenForCloseLibraryPanelEvent().subscribe(() => {
      this.library.close();
    });

    this.eventService.listenForOpenHelpPanelEvent().subscribe(() => {
      this.layout.close();
      this.library.close();
      this.configPanel.close();
      this.agentPanel.close();
      this.helpPanel.open();
    });

    this.eventService.listenForCloseHelpPanelEvent().subscribe(() => {
      this.helpPanel.close();
    });

    this.eventService.listenForOpenAgentPanelEvent().subscribe(() => {
      this.layout.close();
      this.library.close();
      this.configPanel.close();
      this.helpPanel.close();
      this.agentPanel.open();
    });

    this.eventService.listenForCloseAgentPanelEvent().subscribe(() => {
      this.agentPanel.close();
    });

    this.eventService
      .listenForBoardCreatedCompleteEvent()
      .subscribe((event) => {
        this.loadBoards();
      });
    this.eventService
      .listenForBoardDeletedCompleteEvent()
      .subscribe((event) => {
        this.loadBoards();
      });
    this.eventService.listenForBoardUpdateNameDescriptionRequestEvent().subscribe((event) => {
      this.loadBoards();
    });

    this.eventService.listenForBoardSelectedEvent().subscribe((event) => {
      this.selectedBoardId = event.data;
    });
  }
}

<mat-drawer-container class="example-container" autosize>
  @if (boardData.length > 0) {
    @if (navState === 'hidden') {
    <button
      type="button"
      mat-icon-button
      class="nav-edge-toggle nav-reveal"
      (click)="expandNav()"
      matTooltip="Show menu"
      matTooltipPosition="right"
      aria-label="Show board menu">
      <mat-icon>chevron_right</mat-icon>
    </button>
    } @else {
      <button
        type="button"
        mat-icon-button
        class="nav-edge-toggle nav-collapse"
        [style.left.px]="navRailWidthPx"
        (click)="collapseNav()"
        matTooltip="Collapse menu"
        matTooltipPosition="right"
        aria-label="Collapse board menu">
        <mat-icon>chevron_left</mat-icon>
      </button>
    }
  }

  @if (boardData.length > 0) {
    <mat-drawer
    #drawer
    class="example-sidenav"
    [class.collapsed]="navState === 'icon'"
    [class.hidden]="navState === 'hidden'"
    mode="side"
    [opened]="true"
    (transitionend)="onNavRailTransitionEnd($event)">
    <mat-nav-list>
      @for (board of boardData; track board.id) {
        <mat-list-item
          [class.active]="board.id === selectedBoardId"
          [matTooltip]="board.title"
          [matTooltipDisabled]="navExpanded"
          matTooltipPosition="right"
          (click)="selectBoard(board.id)">
          <mat-icon matListItemIcon>{{ board.icon || 'dashboard' }}</mat-icon>
          @if (navExpanded) {
            {{ board.title }}
          }
        </mat-list-item>
      }
    </mat-nav-list>
    </mat-drawer>
  }

  <mat-drawer #layout class="layout-drawer" mode="side" position="end" (openedChange)="onPushDrawerAnimationDone()">
    <app-sidelayout></app-sidelayout>
  </mat-drawer>

  <mat-drawer-container class="config-panel-container">
    <mat-drawer #configPanel mode="over" position="end" (closed)="onConfigPanelClosed()">
      <app-config-panel></app-config-panel>
    </mat-drawer>

    <mat-drawer-container class="library-panel-container">
      <mat-drawer #library mode="over" position="end">
        <app-library></app-library>
      </mat-drawer>

      <mat-drawer-container class="help-panel-container">
        <mat-drawer #helpPanel mode="over" position="end">
          <app-help-panel></app-help-panel>
        </mat-drawer>

        <mat-drawer-container class="agent-panel-container">
          <mat-drawer #agentPanel mode="over" position="end">
            <app-agent-panel></app-agent-panel>
          </mat-drawer>

          <div class="example-sidenav-content">
            <app-board></app-board>
          </div>
        </mat-drawer-container>
      </mat-drawer-container>
    </mat-drawer-container>
  </mat-drawer-container>
</mat-drawer-container>

// web/hosts/react/src/app/sidenav/Sidenav.tsx
import { useEffect, useRef, useState } from 'react';
import Tooltip from '@mui/material/Tooltip';
import { appConfigService } from '../app-config/app-config.service';
import { boardService } from '../board/board.service';
import { eventService } from '../eventservice/event.service';
import { useEventEffect } from 'src/lib/useEventEffect';
import { useObservableValue } from 'src/lib/useObservable';
import { AgentPanel } from '../agent/AgentPanel';
import { Board } from '../board/Board';
import { ConfigPanel } from '../config-panel/ConfigPanel';
import { HelpPanel } from '../help-panel/HelpPanel';
import { Layout } from '../layout/Layout';
import { Library } from '../library/Library';
import { MatIcon } from '../shared/mat-icon/MatIcon';
import { Hiearchy, type IBoard, type IBoardCollection } from '../board/board.model';
import './Sidenav.css';

type PanelName = 'layout' | 'config' | 'library' | 'help' | 'agent' | null;
type NavState = 'expanded' | 'icon' | 'hidden';

/**
 * Ported from armature-ui's SidenavComponent. The Angular original needed
 * five nested mat-drawer-containers because Material doesn't allow two
 * mat-drawers at the same position in one container — every panel here
 * (layout/config/library/help/agent) instead reads from one `openPanel`
 * state value, which gives "opening one closes the others" for free
 * instead of the original's explicit close-the-other-four calls at every
 * open site.
 */
export function Sidenav() {
  const [boardData, setBoardData] = useState<IBoard[]>([]);
  const [selectedBoardId, setSelectedBoardId] = useState<number | null>(null);
  const [navState, setNavState] = useState<NavState>('expanded');
  const [openPanel, setOpenPanel] = useState<PanelName>(null);
  const libraryCollapsed = useObservableValue(
    appConfigService.libraryPanelCollapsed$,
    () => appConfigService.libraryPanelCollapsed
  );

  const lastVisibleNavState = useRef<'expanded' | 'icon'>('expanded');
  const openConfigInstanceId = useRef(-1);
  const previousOpenPanel = useRef<PanelName>(null);

  function loadBoards() {
    boardService.getBoardCollection().subscribe((boardCollection: IBoardCollection) => {
      const parents = boardCollection.boardList.filter((b) => b.relationship === Hiearchy.PARENT);
      setBoardData(parents);

      if (parents.length === 0) {
        setOpenPanel(null);
      }
    });

    boardService.getLastSelectedBoard().subscribe((board) => {
      setSelectedBoardId((current) => current ?? (board && board.id != null ? board.id : current));
    });
  }

  useEffect(() => {
    loadBoards();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // The single reliable "the config panel actually finished closing" signal
  // — fires whether it closed via its own close button, opening a different
  // panel, or the board list becoming empty.
  useEffect(() => {
    if (previousOpenPanel.current === 'config' && openPanel !== 'config') {
      eventService.emitConfigPanelClosedEvent({ data: { instanceId: openConfigInstanceId.current } });
    }
    previousOpenPanel.current = openPanel;
  }, [openPanel]);

  function toggleMenu() {
    setNavState((current) => {
      const next = current === 'hidden' ? lastVisibleNavState.current : current === 'expanded' ? 'icon' : 'expanded';
      lastVisibleNavState.current = next;
      return next;
    });
  }

  function collapseNav() {
    setNavState((current) => {
      if (current !== 'hidden') lastVisibleNavState.current = current;
      return 'hidden';
    });
  }

  function expandNav() {
    setNavState(lastVisibleNavState.current);
  }

  function togglePanel(panel: Exclude<PanelName, null>) {
    setOpenPanel((current) => (current === panel ? null : panel));
  }

  function selectBoard(boardId: number) {
    setSelectedBoardId(boardId);
    eventService.emitBoardSelectedEvent({ data: boardId });
  }

  useEventEffect(eventService.listenForBoardMenuSideNavClickEvent(), () => toggleMenu());
  useEventEffect(eventService.listenForBoardSideLayoutEvent(), () => togglePanel('layout'));

  useEventEffect(eventService.listenForOpenConfigPanelEvent(), (event) => {
    openConfigInstanceId.current = event.data.instanceId;
    setOpenPanel('config');
  });
  useEventEffect(eventService.listenForCloseConfigPanelEvent(), () => {
    setOpenPanel((current) => (current === 'config' ? null : current));
  });

  useEventEffect(eventService.listenForLibraryOpenMenuEvent(), () => togglePanel('library'));
  useEventEffect(eventService.listenForCloseLibraryPanelEvent(), () => {
    setOpenPanel((current) => (current === 'library' ? null : current));
  });

  useEventEffect(eventService.listenForOpenHelpPanelEvent(), () => setOpenPanel('help'));
  useEventEffect(eventService.listenForCloseHelpPanelEvent(), () => {
    setOpenPanel((current) => (current === 'help' ? null : current));
  });

  useEventEffect(eventService.listenForOpenAgentPanelEvent(), () => setOpenPanel('agent'));
  useEventEffect(eventService.listenForCloseAgentPanelEvent(), () => {
    setOpenPanel((current) => (current === 'agent' ? null : current));
  });

  useEventEffect(eventService.listenForBoardCreatedCompleteEvent(), () => loadBoards());
  useEventEffect(eventService.listenForBoardDeletedCompleteEvent(), () => loadBoards());
  useEventEffect(eventService.listenForBoardUpdateNameDescriptionRequestEvent(), () => loadBoards());
  useEventEffect(eventService.listenForBoardSelectedEvent(), (event) => setSelectedBoardId(event.data));

  const navExpanded = navState === 'expanded';
  const navRailWidthPx = navState === 'expanded' ? 220 : 64;

  return (
    <div className="sidenav-root">
      {boardData.length > 0 &&
        (navState === 'hidden' ? (
          <Tooltip title="Show menu" placement="right">
            <button
              type="button"
              className="nav-edge-toggle nav-reveal"
              onClick={expandNav}
              aria-label="Show board menu"
            >
              <MatIcon>chevron_right</MatIcon>
            </button>
          </Tooltip>
        ) : (
          <Tooltip title="Collapse menu" placement="right">
            <button
              type="button"
              className="nav-edge-toggle nav-collapse"
              style={{ left: navRailWidthPx }}
              onClick={collapseNav}
              aria-label="Collapse board menu"
            >
              <MatIcon>chevron_left</MatIcon>
            </button>
          </Tooltip>
        ))}

      {boardData.length > 0 && (
        <nav
          className={[
            'example-sidenav',
            navState === 'icon' ? 'collapsed' : '',
            navState === 'hidden' ? 'hidden' : '',
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <ul className="nav-list">
            {boardData.map((board) => (
              <Tooltip key={board.id} title={board.title} placement="right" disableHoverListener={navExpanded}>
                <li
                  className={board.id === selectedBoardId ? 'active' : ''}
                  aria-current={board.id === selectedBoardId ? 'page' : undefined}
                  onClick={() => selectBoard(board.id)}
                >
                  <MatIcon className="nav-item-icon">{board.icon || 'dashboard'}</MatIcon>
                  {navExpanded && <span className="nav-item-label">{board.title}</span>}
                </li>
              </Tooltip>
            ))}
          </ul>
        </nav>
      )}

      <div className="example-sidenav-content">
        <Board />
      </div>

      {/*
        Every panel below is a mat-drawer position="end" in the Angular
        original, nested so the board sits between the nav rail and
        whichever panel is open — i.e. panels dock to the right edge of the
        screen, not the left. DOM order here (after .example-sidenav-content,
        not before) is what makes that true in a plain flex row: the open
        panel is the flex item closest to the right edge, same as the
        nesting order layout > config > library > help > agent put agent
        closest to the true right edge in the original.
      */}
      <div className={['side-panel-slot', openPanel === 'layout' ? 'open' : ''].filter(Boolean).join(' ')}>
        <Layout />
      </div>

      <div className={['side-panel-slot', openPanel === 'config' ? 'open' : ''].filter(Boolean).join(' ')}>
        <ConfigPanel />
      </div>

      <div
        className={[
          'side-panel-slot',
          openPanel === 'library' ? 'open' : '',
          libraryCollapsed ? 'library-collapsed' : '',
        ]
          .filter(Boolean)
          .join(' ')}
      >
        <Library />
      </div>

      <div className={['side-panel-slot', openPanel === 'help' ? 'open' : ''].filter(Boolean).join(' ')}>
        <HelpPanel />
      </div>

      <div className={['side-panel-slot', openPanel === 'agent' ? 'open' : ''].filter(Boolean).join(' ')}>
        <AgentPanel />
      </div>
    </div>
  );
}
