// web/hosts/react/src/app/gadgets/video/Video.tsx
import { useMemo } from 'react';
import { GadgetCard } from '../common/gadget-common/GadgetCard';
import { useGadgetConfigMode } from '../common/gadget-common/gadget-base/useGadgetConfigMode';
import { getBool, getString } from '../common/gadget-common/gadget-base/gadget.helpers';
import type { GadgetComponentProps } from '../common/gadget-common/gadget-base/gadget-component.types';
import './Video.css';

// Matches an 11-char YouTube video ID out of any of the URL shapes YouTube
// hands out (watch?v=, youtu.be/, /embed/, /shorts/). The video ID itself is
// never trusted verbatim into the iframe src — the embed URL below is always
// rebuilt from the extracted ID, and VALID_ID further constrains its charset.
const YOUTUBE_URL_PATTERN =
  /(?:youtube(?:-nocookie)?\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})(?:[?&/].*)?$/;
const VALID_ID = /^[A-Za-z0-9_-]{11}$/;

function extractVideoId(input: string): string | null {
  const trimmed = input.trim();
  const urlMatch = trimmed.match(YOUTUBE_URL_PATTERN);
  if (urlMatch) return urlMatch[1];
  return VALID_ID.test(trimmed) ? trimmed : null;
}

/** Ported from armature-ui's VideoComponent. */
export function Video({ gadget, onRemove, onPropertyChange }: GadgetComponentProps) {
  const [inConfig, toggleConfigMode] = useGadgetConfigMode(gadget);

  const videoUrl = getString(gadget, 'videoUrl');
  const autoplay = getBool(gadget, 'autoplay');

  const embedUrl = useMemo(() => {
    const videoId = extractVideoId(videoUrl);
    if (!videoId) return null;
    const params = autoplay ? '?autoplay=1&mute=1' : '';
    // youtube-nocookie.com defers tracking cookies until playback starts.
    return `https://www.youtube-nocookie.com/embed/${videoId}${params}`;
  }, [videoUrl, autoplay]);

  return (
    <GadgetCard
      gadget={gadget}
      onRemove={onRemove}
      onPropertyChange={onPropertyChange}
      inConfig={inConfig}
      onToggleConfigMode={toggleConfigMode}
      helpTopic="video"
    >
      {embedUrl ? (
        <iframe
          className="video-frame"
          src={embedUrl}
          title="Video"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        />
      ) : (
        <div className="video-empty">Enter a YouTube URL or video ID in the gadget configuration.</div>
      )}
    </GadgetCard>
  );
}

// src/app/gadgets/video/video.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { BoardService } from 'src/app/board/board.service';
import { EventService } from 'src/app/eventservice/event.service';
import { GadgetBase } from '../common/gadget-common/gadget-base/gadget.base';
import { MatCard, MatCardContent } from '@angular/material/card';
import { CdkDrag } from '@angular/cdk/drag-drop';
import { GadgetHeaderComponent } from '../common/gadget-common/gadget-header/gadget-header.component';

// Matches an 11-char YouTube video ID out of any of the URL shapes YouTube
// hands out (watch?v=, youtu.be/, /embed/, /shorts/). The video ID itself is
// never trusted verbatim into the iframe src — the embed URL below is always
// rebuilt from the extracted ID, and VALID_ID further constrains its charset.
const YOUTUBE_URL_PATTERN =
  /(?:youtube(?:-nocookie)?\.com\/(?:watch\?v=|embed\/|shorts\/)|youtu\.be\/)([A-Za-z0-9_-]{11})(?:[?&/].*)?$/;
const VALID_ID = /^[A-Za-z0-9_-]{11}$/;

@Component({
    selector: 'app-video-gadget',
    templateUrl: './video.component.html',
    styleUrls: ['./video.component.scss'],
    changeDetection: ChangeDetectionStrategy.Eager,
    imports: [MatCard, CdkDrag, GadgetHeaderComponent, MatCardContent]
})
export class VideoComponent extends GadgetBase implements OnInit {
  videoUrl: string = '';
  autoplay: boolean = false;
  embedUrl: SafeResourceUrl | null = null;

  constructor(
    private eventService: EventService,
    private boardService: BoardService,
    private sanitizer: DomSanitizer
  ) {
    super();
  }

  ngOnInit(): void {
    this.loadProperties();
  }

  override initializeConfiguration(gadgetData: any) {
    super.initializeConfiguration(gadgetData);
    this.loadProperties();
  }

  private loadProperties(): void {
    this.videoUrl = this.getString('videoUrl');
    // Uses the same true/'true' idiom every other boolean property does now
    // (previously !!property.value here specifically - a real inconsistency,
    // since a stored string "false" would have rendered as autoplay-on).
    this.autoplay = this.getBool('autoplay');
    this.render();
  }

  private render(): void {
    const videoId = this.extractVideoId(this.videoUrl);
    if (!videoId) {
      this.embedUrl = null;
      return;
    }
    const params = this.autoplay ? '?autoplay=1&mute=1' : '';
    // youtube-nocookie.com defers tracking cookies until playback starts.
    const url = `https://www.youtube-nocookie.com/embed/${videoId}${params}`;
    this.embedUrl = this.sanitizer.bypassSecurityTrustResourceUrl(url);
  }

  private extractVideoId(input: string): string | null {
    const trimmed = input.trim();
    const urlMatch = trimmed.match(YOUTUBE_URL_PATTERN);
    if (urlMatch) return urlMatch[1];
    // Also accept a bare video ID pasted without a surrounding URL.
    return VALID_ID.test(trimmed) ? trimmed : null;
  }

  remove() {
    this.eventService.emitGadgetDeleteEvent({ data: this.instanceId });
  }

  propertyChangeEvent(propertiesJSON: string) {
    this.mergePropertyValues(JSON.parse(propertiesJSON));
    this.loadProperties();
    this.boardService.savePropertyPageConfigurationToDestination(propertiesJSON, this.instanceId);
  }
}
